### ISSUE TITLE
The license is not a part of the npm package

### ISSUE THREAD

**Issue by honzajavorek** [medikoo/duration#5]
Hello, would it be possible to incorporate a full license text into the distributed package? This should be just one `npm publish` away, as the license already is in the repository. I recommend releasing it as a patch version as it is de facto a bug fix and as a patch it virally fixes all projects using this library up the chain.

For many people and companies who care about licenses it is not legally sufficient to only have the SPDX identifier in the `package.json`; a full license text is needed.

**Comment by medikoo** [comment]
Thanks for reporting. Fixed with v0.2.1

**Comment by honzajavorek** [comment]
Thank you!!!
