### ISSUE TITLE
Running tad unit tests in this repo

### ISSUE THREAD

**Issue by amaharana** [medikoo/duration#8]
Haven't seen tad before so need a little help. How do I get the tests to run?

```
$ npm test

> duration@0.2.2 test
> node ./node_modules/tad/bin/tad

21:49:20.752  -  index.js.
                 Error: Cannot find module '/Users/<redacted>/duration/test/__tad'
                 Require stack:
                 - /Users/<redacted>/duration/node_modules/next/module/require-first-in-tree.js
                 - /Users/<redacted>/duration/node_modules/tad/lib/find-context.js
...
```
What should go in the `test/__tad` folder? If I pass it the path to the test file, it doesn't find any test. 🤷‍♂️

```
$ npm test test/index.js

> duration@0.2.2 test
> node ./node_modules/tad/bin/tad


No tests run
```

**Comment by amaharana** [comment]
Never mind, an empty `test/__tad/index.js` file does the trick.

**Comment by medikoo** [comment]
@amaharana I've upgraded `tad` version in a package, and there's no such error anymore.

I've also renamed `master` branch to `main` (sorry for the additional fuss) and configured brand new CI that should help with a process
